src/api/axios.ts, src/components/Header/index.tsx, src/components/Updater/index.tsx, src/contract/token.ts, src/hooks/useGetToken.ts, src/hooks/useUpdateLoginStatus.ts, src/hooks/useWallet.ts, src/pageComponents/invitee/index.tsx, src/pageComponents/layout.tsx, src/pageComponents/points/index.tsx, src/pageComponents/tokensPage/components/TokensHome/index.tsx, src/pageComponents/tokensPage/index.tsx, src/redux/hooks/useGetLoginStatus.ts, src/redux/hooks/useGetStoreInfo.ts, src/redux/reducer/info.ts, src/redux/reducer/loginStatus.ts, src/redux/store.ts, src/redux/types/reducerTypes.ts, src/types/index.ts, src/utils/formattError.ts, src/utils/token.ts, src/utils/walletAndTokenInfo.ts
=> feat: 🎸 change login process

src/components/Header/index.tsx, src/hooks/useGetToken.ts, src/hooks/useUpdateLoginStatus.ts, src/hooks/useWallet.ts, src/pageComponents/assets/index.tsx, src/pageComponents/invitee/index.tsx, src/pageComponents/referral/index.tsx, src/pageComponents/strayCats/index.tsx
change the login logic of the page
=> feat: 🎸 change the login logic of the page

src/hooks/useGetToken.ts
change join verification timing
=> feat: 🎸 change join verification timing

build.config/rewrites/test.js, src/components/HostTag/index.tsx, src/constants/router.ts, src/hooks/useWallet.ts, src/pageComponents/detail/index.tsx, src/pageComponents/tokensPage/components/FilterContainer/style.module.css, src/pageComponents/tokensPage/components/OwnedItems/index.tsx, src/pageComponents/tokensPage/index.tsx, src/pageComponents/tokensPage/type.ts, src/styles/global.css
view the list and details of cat when not loggin
=> feat: 🎸 view the list and details of cat when not loggin

package.json, src/hooks/useGetToken.ts, yarn.lock
change the error text and upgrade aelf-web-login
=> feat: 🎸 change the error text and upgrade aelf-web-login

src/app/my-cats/page.tsx, src/constants/router.ts, src/pageComponents/myCats/components/CheckBoxGroups/index.tsx, src/pageComponents/myCats/components/CheckBoxGroups/style.module.css, src/pageComponents/myCats/components/FilterContainer/index.tsx, src/pageComponents/myCats/components/FilterContainer/style.module.css, src/pageComponents/myCats/components/FilterMenuEmpty/index.tsx, src/pageComponents/myCats/components/FilterTags/index.tsx, src/pageComponents/myCats/components/FilterTags/style.module.css, src/pageComponents/myCats/components/MenuFilter/index.tsx, src/pageComponents/myCats/components/OwnedItems/index.tsx, src/pageComponents/myCats/components/TokensHome/index.tsx, src/pageComponents/myCats/components/TokensHome/style.module.css, src/pageComponents/myCats/components/TokensInfo/index.tsx, src/pageComponents/myCats/components/TokensInfo/styles.module.css, src/pageComponents/myCats/index.tsx, src/pageComponents/myCats/styles.module.css, src/pageComponents/myCats/type.ts
=> feat: 🎸 page split

src/components/OwnedItems/index.tsx, src/hooks/useUpdateLoginStatus.ts, src/hooks/useWallet.ts, src/pageComponents/detail/index.tsx, src/utils/resetAccount.ts
fix detail page interface request multiple times and clear token when logging out
=> fix detail page interface request multiple times and clear token when logging out

src/pageComponents/rank-list/index.tsx
=> feat: 🎸 change header copy

build.config/rewrites/test.js, src/app/rare-cats/page.tsx, src/components/Header/index.tsx, src/components/OwnedItems/index.tsx, src/graphqlServer/hooks/index.ts, src/graphqlServer/queries/index.ts, src/graphqlServer/request/index.ts, src/graphqlServer/types/index.ts, src/pageComponents/rank-list/components/RulesList.tsx, src/pageComponents/rank-list/index.tsx, src/pageComponents/tokensPage/hooks/useGetNoticeData.tsx, src/pageComponents/tokensPage/index.tsx, src/redux/types/reducerTypes.ts, src/types/tokensPage.ts
1. added large transaction reports for all cats on the homepage
2. added ranking reward distribution table
3. added second-level domain name rankings
4. a new "Rare Cats" column is added at the top. After clicking it, all rare cats will be filtered and displayed.
=> Feature/v1.6.0 (#189)

nextLint.yml
=> feat: 🎸 add ci

src/components/EmptyList/components/Banner.tsx, src/components/EmptyList/components/Introduction/index.tsx, src/components/EmptyList/components/IntroductionList/index.tsx, src/components/EmptyList/components/StepCard/index.tsx, src/types/misc.ts
empty data display compatible list style
=> feat: 🎸 empty data display compatible list style

src/components/EmptyList/components/Banner.tsx, src/components/EmptyList/components/Introduction/index.tsx, src/components/EmptyList/components/IntroductionList/index.tsx, src/components/EmptyList/components/StepCard/index.tsx, src/types/misc.ts
Simplified ETransfer usage tutorial. close #222
=> feat: 🎸 empty data display compatible list style (#223)

src/api/request.ts, src/app/events-detail/[id]/page.tsx, src/app/events-detail/page.tsx, src/pageComponents/events-detail/components/BindEvm.tsx, src/pageComponents/events-detail/components/EventsDetailsList.tsx, src/pageComponents/events-detail/components/EventsTable.tsx, src/pageComponents/events-detail/components/HandleCard.tsx, src/pageComponents/events-detail/components/StepsCard.tsx, src/pageComponents/events-detail/components/style.module.css, src/pageComponents/events-detail/index.tsx, src/pageComponents/events-detail/types/type.ts
=> normalized activities

src/api/request.ts, src/app/events-detail/[id]/page.tsx, src/app/events-detail/page.tsx, src/pageComponents/events-detail/components/BindEvm.tsx, src/pageComponents/events-detail/components/EventsDetailsList.tsx, src/pageComponents/events-detail/components/EventsTable.tsx, src/pageComponents/events-detail/components/HandleCard.tsx, src/pageComponents/events-detail/components/StepsCard.tsx, src/pageComponents/events-detail/components/style.module.css, src/pageComponents/events-detail/index.tsx, src/pageComponents/events-detail/types/type.ts
normalized activities. close #238
=> feat: 🎸 normalized activities

src/api/request.ts, src/api/type.d.ts, src/components/EventScrollList/components/EventList.tsx, src/pageComponents/events-detail/components/EventsDetailsList.tsx, src/pageComponents/events-detail/components/StepsCard.tsx, src/pageComponents/events-detail/index.tsx, src/pageComponents/events-detail/types/type.ts
optimize normalized activities
=> optimize normalized activities

src/api/request.ts, src/api/type.d.ts, src/components/EventScrollList/components/EventList.tsx, src/pageComponents/events-detail/components/EventsDetailsList.tsx, src/pageComponents/events-detail/components/StepsCard.tsx, src/pageComponents/events-detail/index.tsx, src/pageComponents/events-detail/types/type.ts
optimize normalized activities. close #243
=> feat: 🎸 optimize normalized activities

.github/workflows/sonarqube.yaml
=> feat: 🎸 add sonarqube

src/pageComponents/events-detail/components/EventsTable.tsx, src/pageComponents/events-detail/types/type.ts
optimize interface parameter transmission
=> feat: 🎸 optimize interface parameter transmission

src/api/axios.ts
solve the problem of empty error reporting. close #291
=> feat: 🎸 solve the problem of empty error reporting

package.json, src/components/OwnedItems/index.tsx, src/hooks/Adopt/useAdoptConfirm.tsx, src/hooks/useResetHandler.ts, src/provider/ForestInitWrapper.tsx, yarn.lock
fix balance display issue and upgrade the SDK. close #295
=> feat: 🎸 fix balance display issue and upgrade the SDK

package.json, src/provider/ForestInitWrapper.tsx, yarn.lock
=> feat: 🎸 upgrade the SDK

.github/workflows/testnet-dev-package.yaml, src/pageComponents/etransfer/styles.module.css
optimize the style of etransfer sdk
=> feat: 🎸 optimize the style of etransfer sdk

.github/workflows/testnet-dev-package.yaml, package.json, src/pageComponents/awaken-swap/index.tsx, yarn.lock
=> feat: 🎸 fix ui and upgrade sdk

build.config/rewrites/test.js, src/graphqlServer/hooks/index.ts, src/graphqlServer/queries/index.ts, src/graphqlServer/request/index.ts, src/graphqlServer/types/index.ts
=> feat: 🎸 change v2

build.config/rewrites/test.js, src/graphqlServer/hooks/index.ts, src/graphqlServer/queries/index.ts, src/graphqlServer/request/index.ts, src/graphqlServer/types/index.ts
integration with aefinder v2. close #343
=> feat: 🎸 integration with aefinder v2

src/hooks/useTelegram.ts, src/hooks/useUserIsInChannel.ts, src/pageComponents/tg-home/index.tsx, src/pageComponents/tg-join-channel/index.tsx
=> Feature/dev v2.17.0 channel

src/pageComponents/tg-join-channel/index.tsx, src/pageComponents/tg-join-channel/style.module.css
fix join button doesn't work the second time
=> fix: fix join button doesn't work the second time

src/hooks/useJoin.ts, src/hooks/useUserIsInChannel.ts, src/pageComponents/tg-home/index.tsx, src/pageComponents/tg-join-channel/index.tsx
stop the modal when user not in channel
=> fix: stop the modal when user not in channel

src/pageComponents/tg-home/hooks/useBalanceService.ts, src/pageComponents/tg-tasks/components/TaskModule/index.tsx, src/pageComponents/tg-tasks/index.tsx
fixed a bug of update the points after claim
=> fix: fixed a bug of update the points after claim

src/hooks/useJoin.ts
=> feat: hide channel verify function

src/pageComponents/tg-battle/components/AdoptModule/index.module.css
=> feat: update vote image url

src/components/TgCollapse/index.tsx, src/pageComponents/tg-battle/components/CompareModule/index.tsx, src/pageComponents/tg-pool/index.module.css, src/pageComponents/tg-pool/index.tsx
=> feat: update cat pool page styles

src/components/TgCollapse/index.tsx, src/components/TgModal/index.tsx, src/hooks/useJoin.ts, src/pageComponents/tg-pool/index.tsx
=> fix: fixed bugs of vote activity

src/pageComponents/tg-battle/components/AdoptModule/index.tsx, src/pageComponents/tg-battle/components/HeaderModule/index.tsx
update the election campaign copy
=> update the election campaign copy

src/pageComponents/tg-home/components/AdoptModule/index.tsx
=> feat: update the spin pool link

src/components/TGAdoptLoading/index.tsx, src/components/TgModal/index.tsx, src/hooks/useAdoptWithVoucher.ts, src/pageComponents/tg-bags/components/AdoptResultModal/index.tsx, src/pageComponents/tg-bags/components/ItemModal/index.tsx, src/pageComponents/tg-bags/components/ItemsModule/index.tsx, src/pageComponents/tg-bags/components/ResultModule/index.tsx, src/pageComponents/tg-bags/index.tsx
fixed a bug when adopt rare cat showing not rare
=> fix: fixed a bug when adopt rare cat showing not rare

src/api/type.d.ts, src/components/CommonModal/index.tsx, src/pageComponents/lucky-spin/components/SpinResultModal/index.tsx, src/pageComponents/lucky-spin/index.tsx, src/pageComponents/tg-bags/components/AdoptResultModal/index.tsx, src/pageComponents/tg-bags/components/ResultModule/index.tsx, src/pageComponents/tg-home/components/AdoptModule/index.tsx, src/pageComponents/tg-spin-pool/components/PoolModule/index.tsx, src/pageComponents/tg-spin-pool/index.tsx
fix: fixed bugs of spin activity
=> fix: fixed bugs of spin activity

src/components/FakeAdoptModal/index.tsx, src/components/FakeAdoptResultModal/index.tsx, src/pageComponents/lucky-spin/components/NoticeModal/index.tsx, src/pageComponents/lucky-spin/index.tsx, src/pageComponents/tg-bags/components/AdoptResultModal/index.tsx, src/pageComponents/tg-bags/components/ItemModal/index.tsx, src/pageComponents/tg-spin-pool/index.tsx
update styles in spin activity
=> fix: update styles in spin activity

src/pageComponents/tg-bags/components/ResultModule/index.tsx
remove traits when it's not rare in adot result
=> feat: remove traits when it's not rare in adot result

src/components/TGAdoptLoading/index.tsx
=> fix: fixed a style bug

src/pageComponents/lucky-spin/components/SpinResultModal/index.tsx, src/pageComponents/lucky-spin/index.tsx, src/pageComponents/tg-home/hooks/useBalanceService.ts, src/redux/hooks/useGetPoints.ts, src/redux/reducer/userInfo.ts
=> fix: fixed points amount bug

src/components/FakeAdoptResultModal/index.tsx
fix: update the link when new user first enter
=> fix: update the link when new user first enter

src/pageComponents/tg-bags/components/ResultModule/index.tsx
=> feat: update adopt result page

src/pageComponents/tg-bags/components/AdoptResultModal/index.tsx, src/pageComponents/tg-bags/components/ResultModule/index.tsx
update the result page when adopt in bags
=> feat: update the result page when adopt in bags

src/hooks/useAdoptWithVoucher.ts, src/hooks/useGetLoginFish.ts, src/hooks/useJoin.ts, src/pageComponents/lucky-spin/index.tsx, src/pageComponents/tg-bags/components/AdoptResultModal/index.tsx, src/pageComponents/tg-bags/components/ResultModule/index.tsx, src/provider/index.tsx, src/redux/types/reducerTypes.ts
optimize the join process. close #410
=> optimize the join process

src/components/Header/components/WithdrawItem.tsx, src/components/Header/index.tsx, src/constants/router.ts, src/pageComponents/tg-home/components/BalanceModule/index.tsx, src/pageComponents/withdraw/index.tsx
=> feat: update the config of withdraw

src/components/Header/index.tsx, src/pageComponents/tg-home/components/BalanceModule/index.tsx
=> feat: hide withdraw

src/api/type.d.ts, src/hooks/useAdoptWithVoucher.ts
=> feat: update adopt params

src/pageComponents/tg-breed/components/Rewards/index.tsx
Fix Data Formatting Issues close #432
=> feat: 🎸 update format

src/pageComponents/tokensPage/index.tsx
=> feat: update merge button style

src/api/request.ts, src/api/type.d.ts, src/components/SyncAdoptModal/index.tsx, src/components/TGAdoptLoading/index.tsx, src/contract/schrodinger.ts, src/pageComponents/tg-breed/components/Notice/index.tsx, src/pageComponents/tg-breed/components/RedeemNotice/index.tsx, src/pageComponents/tg-breed/components/ResultModal/index.tsx, src/pageComponents/tg-breed/components/RewardResult/index.tsx, src/pageComponents/tg-home/components/RewardsCard/index.tsx
=> Feature/dev v2.29.0

src/api/request.ts, src/api/type.d.ts, src/components/SyncAdoptModal/index.tsx, src/components/TGAdoptLoading/index.tsx, src/contract/schrodinger.ts, src/pageComponents/tg-breed/components/Notice/index.tsx, src/pageComponents/tg-breed/components/RedeemNotice/index.tsx, src/pageComponents/tg-breed/components/ResultModal/index.tsx, src/pageComponents/tg-breed/components/RewardResult/index.tsx, src/pageComponents/tg-home/components/RewardsCard/index.tsx
Add redeem functionality. close #444
=> Feature/dev v2.29.0 (#443)

src/api/type.d.ts, src/hooks/Adopt/AdoptStep.ts, src/hooks/useAdoptWithVoucher.ts, src/pageComponents/tg-breed/components/BreedModule/index.tsx
Add toast prompt when system maintenance is in progress. close #448
=> feat: 🎸 add toast prompt when system maintenance is in progress.

src/api/type.d.ts, src/pageComponents/tg-tasks/index.tsx
add partner tasks for telegram bot
=> feat: add partner tasks for telegram bot

src/components/AdoptActionModal/index.tsx, src/pageComponents/tg-home/index.tsx
Resolve the incorrect display of amount and receive token on the Reroll page, and fix the issue where the SGR amount is displayed incorrectly when ELF is 0. close #457
=> feat: update reroll amount display

src/hooks/useDiscoverProvider.ts
feat: update signature recoveryParam
=> feat: update signature recoveryParam
